import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { commandCapabilities } from "../src/core/capabilities";
import { zplCommandDefinitions } from "../web/zplCommandMetadata.generated";

const target = resolve("web/zplDocumentationData.generated.ts");
const indexTarget = resolve("public/zpl-command-index.json");

function documentedDefault(documentation: string): string | undefined {
  const match = documentation.match(/\bDefault(?:s)?\s*:\s*([^.;\n]{1,100})/i)?.[1]
    ?.replace(/\s+/g, " ")
    .trim();
  if (!match) return undefined;
  return match.replace(/\s+(?:Values?|Range)\s*:.*$/i, "").trim() || undefined;
}

const seeds = commandCapabilities.map((capability) => {
  const definition = zplCommandDefinitions[capability.canonical as keyof typeof zplCommandDefinitions];
  return {
    canonical: capability.canonical,
    title: definition.title,
    reference: definition.reference,
    category: capability.category,
    effect: capability.effect,
    scope: capability.scope,
    status: capability.status,
    limitations: capability.limitations ?? [],
    signatures: definition.signatures.map((signature) => ({
      syntax: signature.syntax,
      snippet: signature.snippet,
      ...(signature.label ? { label: signature.label } : {}),
      parameters: signature.parameters.map((parameter) => ({
        key: parameter.key,
        name: parameter.name,
        choices: parameter.choices,
        ...(parameter.enumValues ? { enumValues: parameter.enumValues } : {}),
        ...(parameter.range ? { range: parameter.range } : {}),
        slot: parameter.slot,
        component: parameter.component,
        ...(parameter.syntaxStart === undefined ? {} : { syntaxStart: parameter.syntaxStart }),
        ...(parameter.syntaxEnd === undefined ? {} : { syntaxEnd: parameter.syntaxEnd }),
        ...(parameter.repeatable ? { repeatable: true } : {}),
        ...(parameter.required ? { required: true } : {}),
        ...(documentedDefault(parameter.documentation)
          ? { defaultValue: documentedDefault(parameter.documentation) }
          : {}),
      })),
    })),
  };
});

const output = `// Generated by scripts/generate-command-documentation.ts. Do not edit.
import type {
  CommandCapabilityStatus,
  CommandCategory,
  CommandEffect,
  CommandPersistenceScope,
} from "../src/types/ZplDocument";

export interface ZplDocumentationParameterSeed {
  readonly key: string;
  readonly name: string;
  readonly choices: readonly string[];
  readonly enumValues?: readonly string[];
  readonly range?: { readonly min: number; readonly max: number };
  readonly slot: number;
  readonly component: number;
  readonly syntaxStart?: number;
  readonly syntaxEnd?: number;
  readonly repeatable?: boolean;
  readonly required?: boolean;
  readonly defaultValue?: string;
}

export interface ZplDocumentationSignatureSeed {
  readonly syntax: string;
  readonly snippet: string;
  readonly label?: string;
  readonly parameters: readonly ZplDocumentationParameterSeed[];
}

export interface ZplCommandDocumentationSeed {
  readonly canonical: string;
  readonly title: string;
  readonly reference: string;
  readonly category: CommandCategory;
  readonly effect: CommandEffect;
  readonly scope: CommandPersistenceScope;
  readonly status: Exclude<CommandCapabilityStatus, "unknown">;
  readonly limitations: readonly string[];
  readonly signatures: readonly ZplDocumentationSignatureSeed[];
}

export const zplCommandDocumentationSeeds = ${JSON.stringify(seeds, null, 2)} as const satisfies readonly ZplCommandDocumentationSeed[];
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // A missing generated file is reported as the same deterministic mismatch.
  }
  if (current !== output) {
    console.error("Generated command documentation is stale. Run pnpm docs:commands.");
    process.exitCode = 1;
  } else {
    const {
      zplCommandGuides,
      zplCommandIndexEntry,
    } = await import("../web/zplDocumentation");
    const indexOutput = `${JSON.stringify(zplCommandGuides.map(zplCommandIndexEntry))}\n`;
    let currentIndex = "";
    try {
      currentIndex = readFileSync(indexTarget, "utf8");
    } catch {
      // A missing generated file is reported as the same deterministic mismatch.
    }
    if (currentIndex !== indexOutput) {
      console.error("Generated command documentation is stale. Run pnpm docs:commands.");
      process.exitCode = 1;
    }
  }
} else {
  writeFileSync(target, output);
  const {
    zplCommandGuides,
    zplCommandIndexEntry,
  } = await import("../web/zplDocumentation");
  const indexOutput = `${JSON.stringify(zplCommandGuides.map(zplCommandIndexEntry))}\n`;
  writeFileSync(indexTarget, indexOutput);
}
